### ISSUE TITLE
Expo React Native

### ISSUE THREAD

**Issue by kayode0x** [ospfranco/link-preview-js#102]
I tried using the package on React Native with Expo but I keep running into this error.

```
link-preview-js could not fetch link information TypeError: undefined is not an object (evaluating 'adapter.getParent')
at node_modules/link-preview-js/build/index.js:305:14 in parseResponse
at node_modules/link-preview-js/build/index.js:366:44 in __generator$argument_1
at http://192.168.1.136:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:176314:24 in step
at node_modules/link-preview-js/build/index.js:5:40 in fulfilled
```

I tried multiple URLs but they don't work. Or am I doing something wrong? thanks.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 15

-----

What I tried doing:
```
const parse = (link: string) => {
     getLinkPreview(link, {
            headers: {
                "user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like 
     Gecko) Version/14.0 Mobile/15E148 Safari/604.1",
            },
            timeout: 10000
        }).then((data) => {
            console.debug(data);
        }).catch((err) => {
            console.debug(err);
        });
}
```

----

```
//ranadom sites that support og...
const sites = ["https://www.youtube.com/watch?v=fxqMOXofiF4", "https://medium.com/cybermonkey/automated-versioning-of-react-native-apps-for-play-store-c346c18c9f91", "https://www.instagram.com/p/CVz03bVMIkW/?utm_medium=copy_link", "https://apexwallet.app/dashboard"]

    for (const site of sites) {
        parse(site);
    }

```

**Comment by ospfranco** [comment]
no idea, I don't use expo, you will have to debug the issue yourself
